spring:
  redis:
    cluster:
      host: 127.0.0.1
      port: 7001
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/freshcart?characterEncoding=UTF-8
    username: admin
    password: password
    hikari: maximum-pool-size=20

  flyway:
    enabled: true
    locations: classpath:/db/migration, classpath:com/example/freshcartr
    baseline-on-migrate: true  # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 1

mybatis:
  configuration:
    map-underscore-to-camel-case: true #언더바를(sql문법) 카멜로(자바 객체) 자동 변경
  mapper-locations: classpath:/mapper/**/*.xml

  jpa:
    properties:
      hibernate:

