spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/freshcart
    url: jdbc:mysql://localhost:3306/freshcart?characterEncoding=UTF-8
    username: admin
    password: password

  flyway:
    enabled: true
    locations: classpath:/db/migration, classpath:com/example/freshcart
    baseline-on-migrate: true  # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 1

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.freshcart.domain #마이바티스에서 타입 정보를 사용할 때는 패키지 이름을 적어주어야 하는데, 패키지명 생략 가능

  # 언더바를(sql문법) 카멜로(자바 객체) 자동 변경.