POST http://localhost:8080/stocks/1
Content-Type: application/json

{
  "stock": 10
}

###
POST http://localhost:8080/stocks/3
Content-Type: application/json

{
  "stock": 10
}
###
POST http://localhost:8080/stocks/4
Content-Type: application/json

{
  "stock": 10
}
###
POST http://localhost:8080/stocks/6
Content-Type: application/json

{
  "stock": 10
}
###
POST http://localhost:8080/stocks/7
Content-Type: application/json

{
"stock": 10
}
###
POST http://localhost:8080/stocks/8
Content-Type: application/json

{
  "stock": 10
}