POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "receiverName": "유저1",
  "receiverPhone": "01000000000",
  "receiverAddress": "서울시 강남구 강남대로 22 교보빌딩 1층",
  "cartItems": [
    {
      "productId": 1,
      "count": 1,
      "groups": [
        {
          "optionId": 1
        },
        {
          "optionId": 3
        },
        {
          "optionId": 4
        }
      ]
    },
    {
      "productId": 2,
      "count": 2,
      "groups": [
        {
          "optionId": 6
        },
        {
          "optionId": 7
        },
        {
          "optionId": 8
        }
      ]
    }
  ]
}

###단일 제품 only 주문 요청
POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "receiverName": "유저1",
  "receiverPhone": "01000000000",
  "receiverAddress": "서울시 강남구 강남대로 22 교보빌딩 1층",
  "cartItems": [
    {
      "productId": 3,
      "count": 3
    }
  ]
}

###단일+옵션 제품 주문 요청 (아직 해결 중)
POST http://localhost:8080/orders/register
Content-Type: application/json

{
  "receiverName": "유저1",
  "receiverPhone": "01000000000",
  "receiverAddress": "서울시 강남구 강남대로 22 교보빌딩 1층",
  "cartItems": [
    {
      "productId": 3,
      "count": 3
    },
    {
      "productId": 1,
      "count": 1,
      "groups": [
        {
          "optionId": 1
        },
        {
          "optionId": 3
        },
        {
          "optionId": 4
        }
      ]
    }

  ]
}