POST http://localhost:8080/products/register
Content-Type: application/json

{
  "name":"샐러드",
  "price": 2000,
  "status":"AVAILABLE",
  "description":"맛나요",
  "singleType": false,
  "categoryId": 1,
  "optionSet":
  [
    {   "optionGroupRegister":{
      "optionGroupName": "중량1",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑1",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량2",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑2",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량3",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑3",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량4",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑4",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량5",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑5",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량6",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑6",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량7",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑7",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량8",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑8",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량9",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑9",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량10",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑10",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량11",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑11",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량12",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑12",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량13",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑13",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량14",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑14",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량15",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑15",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량16",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑16",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량17",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑17",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량18",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑18",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량19",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑19",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량20",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑20",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량21",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑21",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량22",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑22",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량23",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑23",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량24",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑24",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량25",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑25",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량26",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑26",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량27",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑27",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량28",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑28",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량29",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑29",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량30",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑30",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량31",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑31",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    },

    {   "optionGroupRegister":{
      "optionGroupName": "중량32",
      "requiredOption": true,
      "exclusive":true,
      "minimumOrder": 1,
      "maximumOrder":1
    },
      "optionDetailRegisterList":
      [
        {
          "name": "30g",
          "price": 0
        },

        {
          "name": "60g",
          "price": 2000
        }
      ]
    },
    {   "optionGroupRegister":{
      "optionGroupName": "토핑32",
      "requiredOption": false,
      "exclusive":false,
      "minimumOrder": 1,
      "maximumOrder":2},
      "optionDetailRegisterList":
      [
        {
          "name": "견과류",
          "price": 1000
        },

        {
          "name": "크랜베리",
          "price": 500
        }
      ]
    }
  ]
}