#회원가입
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "seller@gmail.com",
  "password": "aaaaa",
  "phoneNumber": "123456",
  "name": "SELLER",
  "role": "SELLER"
}

###로그인

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "seller@gmail.com",
  "password": "aaaaa"
}

###로그아웃

POST http://localhost:8080/users/logout
Content-Type: application/json

{
}
